name: Claude PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  claude-review:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '@claude'))
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Claude Code Review
        uses: anthropics/claude-code-action@beta
        with:
          # Use 'code' mode for PR reviews
          mode: code
          
          # Trigger on @claude mention or label
          trigger_phrase: "@claude"
          label_trigger: "claude"
          
          # Custom instructions for PR review
          custom_instructions: |
            You are reviewing a pull request. Please provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            
            Be constructive and helpful in your feedback.
            Focus on the changes in the PR, not the entire codebase.
            
          # Use sticky comment for cleaner PR threads
          use_sticky_comment: true
          
          # Allow Claude to suggest code improvements
          allowed_tools: "edit_file,create_file"
          
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}